version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todolist
    restart: always
    ports:
      - 3308:3306
    # volumes:
    #  - ./mysql/db:/var/lib/mysql